In [129]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [166]:
df   =  pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [131]:
df['Name'] = df['Name'].str.lower()
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"braund, mr. owen harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"allen, mr. william henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"montvila, rev. juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"graham, miss. margaret edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"johnston, miss. catherine helen ""carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"behr, mr. karl howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"dooley, mr. patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [132]:
df['Name1'] =  df['Name'].str.split()
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name1
0,1,0,3,"braund, mr. owen harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"[braund,, mr., owen, harris]"
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"[cumings,, mrs., john, bradley, (florence, bri..."
2,3,1,3,"heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"[heikkinen,, miss., laina]"
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.0,1,0,113803,53.1000,C123,S,"[futrelle,, mrs., jacques, heath, (lily, may, ..."
4,5,0,3,"allen, mr. william henry",male,35.0,0,0,373450,8.0500,NaN,S,"[allen,, mr., william, henry]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"montvila, rev. juozas",male,27.0,0,0,211536,13.0000,NaN,S,"[montvila,, rev., juozas]"
887,888,1,1,"graham, miss. margaret edith",female,19.0,0,0,112053,30.0000,B42,S,"[graham,, miss., margaret, edith]"
888,889,0,3,"johnston, miss. catherine helen ""carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,"[johnston,, miss., catherine, helen, ""carrie""]"
889,890,1,1,"behr, mr. karl howell",male,26.0,0,0,111369,30.0000,C148,C,"[behr,, mr., karl, howell]"
890,891,0,3,"dooley, mr. patrick",male,32.0,0,0,370376,7.7500,NaN,Q,"[dooley,, mr., patrick]"

In [133]:
df['Name1'] = df['Name'].str.replace('mr.', 'x')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name1
0,1,0,3,"braund, mr. owen harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"braund, x owen harris"
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"cumings, mrs. john bradley (florence briggs th..."
2,3,1,3,"heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"heikkinen, miss. laina"
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.0,1,0,113803,53.1000,C123,S,"futrelle, mrs. jacques heath (lily may peel)"
4,5,0,3,"allen, mr. william henry",male,35.0,0,0,373450,8.0500,NaN,S,"allen, x william henry"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"montvila, rev. juozas",male,27.0,0,0,211536,13.0000,NaN,S,"montvila, rev. juozas"
887,888,1,1,"graham, miss. margaret edith",female,19.0,0,0,112053,30.0000,B42,S,"graham, miss. margaret edith"
888,889,0,3,"johnston, miss. catherine helen ""carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,"johnston, miss. catherine helen ""carrie"""
889,890,1,1,"behr, mr. karl howell",male,26.0,0,0,111369,30.0000,C148,C,"behr, x karl howell"
890,891,0,3,"dooley, mr. patrick",male,32.0,0,0,370376,7.7500,NaN,Q,"dooley, x patrick"

In [134]:
# df['Name1'] = df['Name'].str.replace('mr.', 'x')
df['Name1'] = df['Name1'].str.replace(r"[()]", "", regex=True)

In [135]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name1
0,1,0,3,"braund, mr. owen harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"braund, x owen harris"
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"cumings, mrs. john bradley florence briggs thayer"
2,3,1,3,"heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"heikkinen, miss. laina"
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.0,1,0,113803,53.1000,C123,S,"futrelle, mrs. jacques heath lily may peel"
4,5,0,3,"allen, mr. william henry",male,35.0,0,0,373450,8.0500,NaN,S,"allen, x william henry"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"montvila, rev. juozas",male,27.0,0,0,211536,13.0000,NaN,S,"montvila, rev. juozas"
887,888,1,1,"graham, miss. margaret edith",female,19.0,0,0,112053,30.0000,B42,S,"graham, miss. margaret edith"
888,889,0,3,"johnston, miss. catherine helen ""carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,"johnston, miss. catherine helen ""carrie"""
889,890,1,1,"behr, mr. karl howell",male,26.0,0,0,111369,30.0000,C148,C,"behr, x karl howell"
890,891,0,3,"dooley, mr. patrick",male,32.0,0,0,370376,7.7500,NaN,Q,"dooley, x patrick"

In [136]:
df['Name1'] = df['Name1'].str.replace('"','')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name1
0,1,0,3,"braund, mr. owen harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"braund, x owen harris"
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"cumings, mrs. john bradley florence briggs thayer"
2,3,1,3,"heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"heikkinen, miss. laina"
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.0,1,0,113803,53.1000,C123,S,"futrelle, mrs. jacques heath lily may peel"
4,5,0,3,"allen, mr. william henry",male,35.0,0,0,373450,8.0500,NaN,S,"allen, x william henry"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"montvila, rev. juozas",male,27.0,0,0,211536,13.0000,NaN,S,"montvila, rev. juozas"
887,888,1,1,"graham, miss. margaret edith",female,19.0,0,0,112053,30.0000,B42,S,"graham, miss. margaret edith"
888,889,0,3,"johnston, miss. catherine helen ""carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,"johnston, miss. catherine helen carrie"
889,890,1,1,"behr, mr. karl howell",male,26.0,0,0,111369,30.0000,C148,C,"behr, x karl howell"
890,891,0,3,"dooley, mr. patrick",male,32.0,0,0,370376,7.7500,NaN,Q,"dooley, x patrick"

In [137]:
print(df['Cabin'].isnull().value_counts())
print(df['Cabin'].value_counts())

print(df['Cabin'])

Cabin
True     687
False    204
Name: count, dtype: int64
Cabin
G6             4
C23 C25 C27    4
B96 B98        4
F2             3
D              3
              ..
E17            1
A24            1
C50            1
B42            1
C148           1
Name: count, Length: 147, dtype: int64
0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [138]:
df['Cabin'] = df['Cabin'].str.split().str[0]
df['Cabin'].value_counts()

Cabin
G6      4
F       4
C23     4
B96     4
F33     3
       ..
E17     1
A24     1
C50     1
B42     1
C148    1
Name: count, Length: 145, dtype: int64

In [139]:
df[df['Cabin'].str.startswith('F', na=False)].value_counts("Cabin")

Cabin
F      4
F2     3
F33    3
F4     2
F38    1
Name: count, dtype: int64

In [141]:
print(pd.crosstab(df['Pclass'], df['Deck']))

Deck     A   B   C   D   E  F  G  T
Pclass
1       15  47  59  29  25  0  0  1
2        0   0   0   4   4  8  0  0
3        0   0   0   0   3  5  4  0

In [144]:
df_clean = df[df.notnull().all(axis=1)]
traning_drok =  df_clean['Cabin'].str[0]
traning_drok.value_counts()

Cabin
C    51
B    43
D    31
E    30
A    12
F    11
G     4
T     1
Name: count, dtype: int64

In [147]:
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name1,Deck
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"cumings, mrs. john bradley florence briggs thayer",C
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.0,1,0,113803,53.1000,C123,S,"futrelle, mrs. jacques heath lily may peel",C
6,7,0,1,"mccarthy, mr. timothy j",male,54.0,0,0,17463,51.8625,E46,S,"mccarthy, x timothy j",E
10,11,1,3,"sandstrom, miss. marguerite rut",female,4.0,1,1,PP 9549,16.7000,G6,S,"sandstrom, miss. marguerite rut",G
11,12,1,1,"bonnell, miss. elizabeth",female,58.0,0,0,113783,26.5500,C103,S,"bonnell, miss. elizabeth",C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"beckwith, mrs. richard leonard (sallie monypeny)",female,47.0,1,1,11751,52.5542,D35,S,"beckwith, mrs. richard leonard sallie monypeny",D
872,873,0,1,"carlsson, mr. frans olof",male,33.0,0,0,695,5.0000,B51,S,"carlsson, x frans olof",B
879,880,1,1,"potter, mrs. thomas jr (lily alexenia wilson)",female,56.0,0,1,11767,83.1583,C50,C,"potter, mrs. thomas jr lily alexenia wilson",C
887,888,1,1,"graham, miss. margaret edith",female,19.0,0,0,112053,30.0000,B42,S,"graham, miss. margaret edith",B
889,890,1,1,"behr, mr. karl howell",male,26.0,0,0,111369,30.0000,C148,C,"behr, x karl howell",C

In [148]:
df['Age'].isnull().value_counts()

Age
False    714
True     177
Name: count, dtype: int64

In [169]:
idex = df[df['Embarked'].isnull()].index

In [170]:
df = df.drop(index=idex)

In [171]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Braund Mr Owen Harris,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,Cumings Mrs John Bradley Florence Briggs Thayer,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,Heikkinen Miss Laina,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,Futrelle Mrs Jacques Heath Lily May Peel,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,Allen Mr William Henry,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,Montvila Rev Juozas,male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,Graham Miss Margaret Edith,female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,Johnston Miss Catherine Helen Carrie,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,Behr Mr Karl Howell,male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,Dooley Mr Patrick,male,32.0,0,0,370376,7.7500,NaN,Q

In [152]:
df['Name'] = df['Name'].str.lower()

In [153]:
df['Name'] = df['Name'].str.strip()

In [154]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name1,Deck
0,1,0,3,"braund, mr. owen harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"braund, x owen harris",NaN
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"cumings, mrs. john bradley florence briggs thayer",C
2,3,1,3,"heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"heikkinen, miss. laina",NaN
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.0,1,0,113803,53.1000,C123,S,"futrelle, mrs. jacques heath lily may peel",C
4,5,0,3,"allen, mr. william henry",male,35.0,0,0,373450,8.0500,NaN,S,"allen, x william henry",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"montvila, rev. juozas",male,27.0,0,0,211536,13.0000,NaN,S,"montvila, rev. juozas",NaN
887,888,1,1,"graham, miss. margaret edith",female,19.0,0,0,112053,30.0000,B42,S,"graham, miss. margaret edith",B
888,889,0,3,"johnston, miss. catherine helen ""carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,"johnston, miss. catherine helen carrie",NaN
889,890,1,1,"behr, mr. karl howell",male,26.0,0,0,111369,30.0000,C148,C,"behr, x karl howell",C
890,891,0,3,"dooley, mr. patrick",male,32.0,0,0,370376,7.7500,NaN,Q,"dooley, x patrick",NaN

In [167]:
df['Name'] =  df['Name'].str.replace(r"[^\w\s]","",regex=True)

In [168]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Braund Mr Owen Harris,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,Cumings Mrs John Bradley Florence Briggs Thayer,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,Heikkinen Miss Laina,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,Futrelle Mrs Jacques Heath Lily May Peel,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,Allen Mr William Henry,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,Montvila Rev Juozas,male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,Graham Miss Margaret Edith,female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,Johnston Miss Catherine Helen Carrie,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,Behr Mr Karl Howell,male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,Dooley Mr Patrick,male,32.0,0,0,370376,7.7500,NaN,Q

In [157]:
df['Ticket']

0             A/5 21171
1              PC 17599
2      STON/O2. 3101282
3                113803
4                373450
             ...
886              211536
887              112053
888          W./C. 6607
889              111369
890              370376
Name: Ticket, Length: 889, dtype: object

In [174]:
df_age =  df[['PassengerId','Survived','Pclass','Name','Sex','SibSp','Parch','Ticket','Fare','Embarked','Age']]

In [175]:
df_age

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Embarked,Age
0,1,0,3,Braund Mr Owen Harris,male,1,0,A/5 21171,7.2500,S,22.0
1,2,1,1,Cumings Mrs John Bradley Florence Briggs Thayer,female,1,0,PC 17599,71.2833,C,38.0
2,3,1,3,Heikkinen Miss Laina,female,0,0,STON/O2. 3101282,7.9250,S,26.0
3,4,1,1,Futrelle Mrs Jacques Heath Lily May Peel,female,1,0,113803,53.1000,S,35.0
4,5,0,3,Allen Mr William Henry,male,0,0,373450,8.0500,S,35.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,Montvila Rev Juozas,male,0,0,211536,13.0000,S,27.0
887,888,1,1,Graham Miss Margaret Edith,female,0,0,112053,30.0000,S,19.0
888,889,0,3,Johnston Miss Catherine Helen Carrie,female,1,2,W./C. 6607,23.4500,S,NaN
889,890,1,1,Behr Mr Karl Howell,male,0,0,111369,30.0000,C,26.0
890,891,0,3,Dooley Mr Patrick,male,0,0,370376,7.7500,Q,32.0

In [176]:
df_age['Ticket']  = df_age['Ticket'].str.strip()
df_age['Ticket']  = df_age['Ticket'].str.lower()

/tmp/ipykernel_5550/3640563751.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_age['Ticket']  = df_age['Ticket'].str.strip()
/tmp/ipykernel_5550/3640563751.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_age['Ticket']  = df_age['Ticket'].str.lower()

In [177]:
df_age["prefix"] = df_age["Ticket"].str.extract(r"([A-Za-z./]+)")
df_age["ticket_nember"] =  df_age["Ticket"].str.extract(r'(\d+)$')

In [178]:
df_age["prefix"] = df_age["prefix"].fillna('unknown')
df_age["ticket_nember"] = df_age["ticket_nember"].fillna(0).astype(int)

In [179]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_age['Name'] = le.fit_transform(df_age['Name'])
df_age['Sex'] = le.fit_transform(df_age['Sex'])
df_age['Ticket'] = le.fit_transform(df_age['Ticket'])
df_age['Embarked'] = le.fit_transform(df_age['Embarked'])
df_age['prefix'] = le.fit_transform(df_age['prefix'])

In [187]:
predictors = ['PassengerId','Survived','Pclass','Name','Sex','SibSp','Parch','Ticket','Fare','Embarked']
x_traing =  df_age[df_age['Age'].notnull()][predictors]
y_traing =  df_age[df_age['Age'].notnull()]['Age']
x_testing =  df_age[df_age['Age'].isnull()][predictors]

In [188]:
x_testing

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Embarked
5,6,0,3,553,1,0,0,274,8.4583,1
17,18,1,2,865,1,0,0,150,13.0000,2
19,20,1,3,511,0,0,0,183,7.2250,0
26,27,0,3,240,1,0,0,178,7.2250,0
28,29,1,3,604,0,0,0,282,7.8792,1
...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,671,1,0,0,177,7.2292,0
863,864,0,3,717,0,8,2,567,69.5500,2
868,869,0,3,888,1,0,0,308,9.5000,2
878,879,0,3,450,1,0,0,362,7.8958,2
888,889,0,3,412,0,1,2,674,23.4500,2

In [190]:
from sklearn.ensemble import RandomForestRegressor
model =  RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(x_traing, y_traing)

RandomForestRegressor(random_state=42)

In [193]:
predicted_ages = model.predict(x_testing)

In [194]:
predicted_ages

array([27.325 , 42.7   , 17.18  , 32.645 , 18.455 , 28.73  , 38.84  ,
       19.275 , 21.735 , 29.33  , 27.44  , 32.82  , 20.36  , 22.2125,
       41.88  , 48.27  , 13.0369, 26.47  , 32.08  , 18.08  , 23.98  ,
       33.765 , 28.075 , 27.205 , 25.565 , 32.63  , 39.38  , 10.2067,
       28.2233, 29.12  , 29.9   , 11.34  , 31.29  , 51.72  ,  4.72  ,
       12.18  , 27.935 , 42.5   , 25.57  , 32.46  , 20.9   , 11.56  ,
       29.73  , 26.2   ,  5.43  , 26.635 , 21.195 , 22.71  , 28.15  ,
       38.78  , 31.965 , 29.885 , 42.48  , 23.15  , 34.835 , 50.225 ,
       51.6   , 41.985 , 23.68  , 26.23  , 35.88  , 28.87  , 33.87  ,
       11.37  , 23.025 , 37.99  , 27.88  , 29.9   , 53.785 , 32.835 ,
       22.22  , 22.835 , 29.775 , 18.805 , 23.82  , 29.96  , 26.825 ,
       30.465 ,  6.0875, 29.125 , 25.84  , 32.84  , 28.215 , 28.66  ,
       31.395 , 31.06  , 36.155 , 30.795 , 26.535 , 33.89  , 42.62  ,
       30.64  , 33.145 , 32.61  , 29.15  , 28.68  , 37.485 , 32.52  ,
        7.16  , 26.985 , 28.845 , 30.91  , 27.17  , 38.02  , 28.955 ,
       29.58  , 32.255 , 28.86  , 36.7   , 33.165 , 11.4793, 29.45  ,
       29.33  , 30.875 , 30.7   , 31.99  , 30.505 , 30.9   , 29.095 ,
       24.365 , 23.415 , 27.37  , 29.42  , 26.125 , 32.115 , 28.51  ,
       26.235 , 40.16  , 36.2   , 23.775 , 31.44  , 33.93  , 44.9   ,
       30.005 , 26.87  , 34.395 , 25.535 , 20.25  , 24.2   , 26.585 ,
       44.    , 38.665 , 22.705 , 28.06  , 21.965 , 11.3524, 43.91  ,
       29.705 , 23.06  , 39.75  , 25.56  , 24.52  , 39.66  , 25.99  ,
       33.84  , 29.18  , 26.76  , 33.635 , 31.22  , 29.08  , 33.33  ,
       13.03  , 36.72  , 38.71  , 29.315 , 28.63  , 27.125 , 28.05  ,
       29.295 , 36.58  , 11.4   , 42.85  , 38.325 , 11.96  , 40.51  ,
       29.885 , 29.75  ])

In [ ]:

import xgboost as xgb
model1 = xgb.XGBRegressor(
    n_estimators=100,   
    learning_rate=0.1,  
    max_depth=3,       
    random_state=42
)